### ISSUE TITLE
Bundle npm modules into your Lambdas clarification

### ISSUE THREAD

**Issue by ivanovj** [Superformula/node-backend-test#13]
The README states "Bundle npm modules into your Lambdas", do you guys mean the actual dependencies (i.e. their code)? Or just to lock their versions (in package(-lock).json for example)? I would recommend the latter as best practice.

Thank you
J

**Comment by afaq-sf** [comment]
The intent is not to imply the `how` of package.json vs lock file but rather give the candidate an opportunity to demonstrate familiarity with lambda package patterns. These can include but are not limited to:

- Using Lambda Layers for sharing dependencies rather than packaging node_modules in-line 
- Demonstrating familiarity with Lambda package limits, alternative paths, and impact from it 
- Removing built-in Lambda packages like aws-sdk
- caching dependency via CI/CD
- etc.


Great question. And fair point on the unclear wording. 
We'll have to clarify on that bonus requirement to make it clearer. 

Thank you
